---
deployment:
  tasks:
    # 1. Deploy Direto do Master (SGIM-VENDAS)
    - /bin/cp -R SGIM-VENDAS/* /home1/hg9a3205/public_html/
    
    # 2. Deploy Direto do Cliente (SGIM-CLIENTE)
    - /bin/cp SGIM-CLIENTE/atualizacoes.php /home1/hg9a3205/public_html/
    - /bin/cp SGIM-CLIENTE/includes/header.php /home1/hg9a3205/public_html/includes/
