-- MIGRATION: Vazio por segurança para evitar travamento do instalador antigo
-- As tabelas e permissões já foram validadas.
-- Este arquivo está vazio para garantir que o fluxo de atualização finalize corretamente no banco de dados.
